spring:
  application:
    name: rag

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RAG
    username: santer
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: 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
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4o-mini
          max-tokens: 100

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
